- name: Add Mojo deps
  apt: name={{item}} 
  with_items: ['openjdk-7-jre-headless','libgtk2.0-0', 'linux-image-extra-virtual' ]
  tags: [mojo]

- name: Install mojo loader
  unarchive:
    src: https://embeddedmicro.com/media/wysiwyg/mojo-loader/mojo-loader-1.3.0-linux64.tgz
    dest: /opt/mojo
    remote_src: yes
    creates: /opt/mojo/mojo-loader-1.3.0/driver/99-mojo.rules

- name: Give vagrant serial access
  shell: usermod -a -G dialout vagrant

- name: Enable Mojo Driver
  copy:
    src: /opt/mojo/mojo-loader-1.3.0/driver/99-mojo.rules
    dest: /etc/udev/rules.d/98-mojo.rules
    owner: root
    group: root
    mode: 0644

- name: Reload udev
  shell: udevadm control --reload

- name: add {{mojo_path}} to path
  vars:
    mojo_path: /opt/mojo/mojo-loader-1.3.0
  lineinfile: >
   dest=/etc/environment
   state=present
   backrefs=yes
   regexp='PATH=(["]*)((?!.*?{{mojo_path}}).*?)(["]*)$'
   line="PATH=\1\2:{{mojo_path}}\3"

